

var direction = "rtl";

var howToPlay = "";

var alphabet = ['أ', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و','ي', 'ؤ', 'ئ', 'إ', 'ا', 'ء' ,'ى', 'آ', 'ة'];

// Table of unicode order used for the keyboard control and accepted by the game [1568-1594] [1561-1610] 
var unicodeTable =  ["ء","آ","أ","ؤ","إ","ئ","ا","ب","ة","ت","ث","ج","ح","خ","د","ذ","ر","ز","س","ش","ص","ض","ط","ظ","ع","غ", "","","","","","ـ", "ف", "ق","ك","ل","م","ن","ه","و","ى","ي"];

var levels = ["Novice", "Beginner", "Intermediate", "Advanced", "Encyclopedic"];

var categoriesInfo = [
  {"title":"Surahs","zOption":"","status":"selected", "doc":""},
  {"title":"Names of God","zOption":"","status":"selected", "doc":"http://www.almaany.com/en/dict/ar-en/"},
  {"title":"Prophets","zOption":"","status":"selected", "doc":""},
  {"title":"Sahaba","zOption":"","status":"selected", "doc":""},
  {"title":"Religious term","zOption":"","status":"", "doc":"http://www.almaany.com/en/dict/ar-en/"},
  {"title":"Farm animals","zOption":"","status":"selected", "doc":"http://www.almaany.com/en/dict/ar-en/"},
  {"title":"Zoo animals","zOption":"","status":"", "doc":"http://www.almaany.com/en/dict/ar-en/"},
  {"title":"Arab countries","zOption":"","status":"selected", "doc":"http://www.almaany.com/en/dict/ar-en/"},
  {"title":"Famous cities","zOption":"","status":"", "doc":"http://www.almaany.com/en/dict/ar-en/"},
  {"title":"Colors","zOption":"","status":"selected", "doc":"http://www.almaany.com/en/dict/ar-en/"},
  {"title":"fruits","zOption":"","status":"", "doc":"http://www.almaany.com/en/dict/ar-en/"},
  {"title":"Vegetables","zOption":"","status":"", "doc":"http://www.almaany.com/en/dict/ar-en/"},
  {"title":"Plants kind","zOption":"","status":"", "doc":"http://www.almaany.com/en/dict/ar-en/"},
  {"title":"House","zOption":"","status":"", "doc":"http://www.almaany.com/en/dict/ar-en/"},
  {"title":"Family","zOption":"","status":"", "doc":"http://www.almaany.com/en/dict/ar-en/"},
  {"title":"Food and drinks","zOption":"","status":"disabled", "doc":"http://www.almaany.com/en/dict/ar-en/"},
  {"title":"tools and instruments","zOption":"","status":"disabled", "doc":"http://www.almaany.com/en/dict/ar-en/"},
];

var categories = [

[
  {"word":"الفاتحة", "hint":"The Opening", "indication":"", "level":"0"},
  {"word":"البقرة", "hint":"The Calf, The Cow", "indication":"", "level":"0"},
  {"word":"آل عمران", "hint":"The Family ofImran, The House of 'Imrán", "indication":"", "level":"0"},
  {"word":"النساء", "hint":"The Women", "indication":"", "level":"0"},
  {"word":"المائدة", "hint":"The Food, The Repast, The Table", "indication":"", "level":"0"},
  {"word":"الأنعام", "hint":"The Cattle", "indication":"", "level":"0"},
  {"word":"الأعراف", "hint":"The Heights, The Faculty of Discernment", "indication":"", "level":"0"},
  {"word":"الأنفال", "hint":"The Spoils of War", "indication":"", "level":"0"},
  {"word":"التوبة", "hint":"The Repentance", "indication":"", "level":"0"},
  {"word":"يونس", "hint":"Jonah", "indication":"", "level":"0"},
  {"word":"هود", "hint":"Hud", "indication":"", "level":"0"},
  {"word":"يوسف", "hint":"Joseph", "indication":"", "level":"0"},
  {"word":"الرعد", "hint":"The Thunder", "indication":"", "level":"0"},
  {"word":"إبراهيم", "hint":"Abraham", "indication":"", "level":"0"},
  {"word":"الحجر", "hint":"The Rocky Tract, The Stoneland, The Rock City, Al-Hijr", "indication":"", "level":"0"},
  {"word":"النحل", "hint":"The Honey Bees, The Bee", "indication":"", "level":"0"},
  {"word":"الإسراء", "hint":"The Night Journey", "indication":"", "level":"0"},
  {"word":"الكهف", "hint":"The Cave", "indication":"", "level":"0"},
  {"word":"مريم", "hint":"Mary", "indication":"", "level":"0"},
  {"word":"طه", "hint":"Ta-Ha", "indication":"", "level":"0"},
  {"word":"الأنبياء", "hint":"The Prophets", "indication":"", "level":"0"},
  {"word":"الحج", "hint":"The Pilgrimage", "indication":"", "level":"0"},
  {"word":"المؤمنون", "hint":"The Believers", "indication":"", "level":"0"},
  {"word":"النور", "hint":"The Light", "indication":"", "level":"0"},
  {"word":"الفرقان", "hint":"The Criterion, The Standard, The Standard of True and False", "indication":"", "level":"0"},
  {"word":"الشعراء", "hint":"The Poets", "indication":"", "level":"0"},
  {"word":"النمل", "hint":"The Ant, The Ants", "indication":"", "level":"0"},
  {"word":"القصص", "hint":"The Narrations, The Stories, The Story", "indication":"", "level":"0"},
  {"word":"العنكبوت", "hint":"The Spider", "indication":"", "level":"0"},
  {"word":"الروم", "hint":"The Romans, The Byzantines", "indication":"", "level":"0"},
  {"word":"لقمان", "hint":"Luqman", "indication":"", "level":"0"},
  {"word":"السجدة", "hint":"The Prostration, Worship, Adoration", "indication":"", "level":"0"},
  {"word":"الأحزاب", "hint":"The Clans, The Confederates, The Combined Forces", "indication":"", "level":"0"},
  {"word":"سبأ", "hint":"Sheba", "indication":"", "level":"0"},
  {"word":"فاطر", "hint":"The Originator", "indication":"", "level":"0"},
  {"word":"يس", "hint":"Ya Seen", "indication":"", "level":"0"},
  {"word":"الصافات", "hint":"Those Who Set The Ranks, Drawn Up In Ranks, Those Ranged in Ranks", "indication":"", "level":"0"},
  {"word":"ص", "hint":"Sad", "indication":"", "level":"0"},
  {"word":"الزمر", "hint":"The Crowds, The Troops, Throngs", "indication":"", "level":"0"},
  {"word":"غافر", "hint":"The Forgiver (God), Forgiving", "indication":"", "level":"0"},
  {"word":"فصلت", "hint":"Expounded, Explained In Detail, Clearly Spelled Out", "indication":"", "level":"0"},
  {"word":"الشورى", "hint":"The Consultation", "indication":"", "level":"0"},
  {"word":"الزخرف", "hint":"The Gold Adornments, The Ornaments of Gold, Luxury, Gold", "indication":"", "level":"0"},
  {"word":"الدخان", "hint":"The Smoke", "indication":"", "level":"0"},
  {"word":"الجاثية", "hint":"The Kneeling Down, Crouching", "indication":"", "level":"0"},
  {"word":"الأحقاف", "hint":"Winding Sand-tracts, The Dunes, The Sand-Dunes", "indication":"", "level":"0"},
  {"word":"محمد", "hint":"Muhammad", "indication":"", "level":"0"},
  {"word":"الفتح", "hint":"The Victory, Conquest", "indication":"", "level":"0"},
  {"word":"الحجرات", "hint":"The Private Apartments, The Inner Apartments", "indication":"", "level":"0"},
  {"word":"ق", "hint":"Qaf", "indication":"", "level":"0"},
  {"word":"الذاريات", "hint":"The Wind That Scatter, The Winnowing Winds, The Dust-Scattering Winds", "indication":"", "level":"0"},
  {"word":"الطور", "hint":"The Mount, Mount Sinai", "indication":"", "level":"0"},
  {"word":"النجم", "hint":"The Star, The Unfolding", "indication":"", "level":"0"},
  {"word":"القمر", "hint":"The Moon", "indication":"", "level":"0"},
  {"word":"الرحمن", "hint":"The Most Merciful, The Most Gracious", "indication":"", "level":"0"},
  {"word":"الواقعة", "hint":"The Inevitable, The Event, That Which Must Come to Pass", "indication":"", "level":"0"},
  {"word":"الحديد", "hint":"The Iron", "indication":"", "level":"0"},
  {"word":"المجادلة", "hint":"The Pleading, The Pleading Woman", "indication":"", "level":"0"},
  {"word":"الحشر", "hint":"The Mustering, The Gathering, Exile, Banishment", "indication":"", "level":"0"},
  {"word":"الممتحنة", "hint":"The Examined One, She That Is To Be Examined", "indication":"", "level":"0"},
  {"word":"الصف", "hint":"The Ranks, Battle Array", "indication":"", "level":"0"},
  {"word":"الجمعة", "hint":"The Congregation, Friday", "indication":"", "level":"0"},
  {"word":"المنافقون", "hint":"The Hypocrites", "indication":"", "level":"0"},
  {"word":"التغابن", "hint":"The Cheating, The Mutual Disillusion, The Mutual Loss and Gain, Loss and Gain", "indication":"", "level":"0"},
  {"word":"الطلاق", "hint":"Divorce", "indication":"", "level":"0"},
  {"word":"التحريم", "hint":"The Prohibition", "indication":"", "level":"0"},
  {"word":"الملك", "hint":"The Dominion, Sovereignty, Control", "indication":"", "level":"0"},
  {"word":"القلم", "hint":"The Pen", "indication":"", "level":"0"},
  {"word":"الحاقة", "hint":"The Sure Reality, The Laying-Bare of the Truth", "indication":"", "level":"0"},
  {"word":"المعارج", "hint":"The Ways of Ascent, The Ascending Stairways", "indication":"", "level":"0"},
  {"word":"نوح", "hint":"Noah", "indication":"", "level":"0"},
  {"word":"الجن", "hint":"The Spirits, The Unseen Beings", "indication":"", "level":"0"},
  {"word":"المزمل", "hint":"The Enfolded One, The Enshrouded One, Bundled Up, The Enwrapped One", "indication":"", "level":"0"},
  {"word":"المدثر", "hint":"The One Wrapped Up, The Cloaked One, The Man Wearing A Cloak, The Enfolded One", "indication":"", "level":"0"},
  {"word":"القيامة", "hint":"Resurrection, The Day of Resurrection, Rising Of The Dead", "indication":"", "level":"0"},
  {"word":"الإنسان", "hint":"The Human, Man", "indication":"", "level":"0"},
  {"word":"المرسلات", "hint":"Those Sent Forth, The Emissaries, Winds Sent Forth", "indication":"", "level":"0"},
  {"word":"النبأ", "hint":"The Great News, The Announcement, The Tiding", "indication":"", "level":"0"},
  {"word":"النازعات", "hint":"Those Who Tear Out, Those Who Drag Forth, Soul-snatchers, Those That Rise", "indication":"", "level":"0"},
  {"word":"عبس", "hint":"He Frowned", "indication":"", "level":"0"},
  {"word":"التكوير", "hint":"The Folding Up, The Overthrowing, Shrouding in Darkness", "indication":"", "level":"0"},
  {"word":"الإنفطار", "hint":"The Cleaving Asunder, Bursting Apart", "indication":"", "level":"0"},
  {"word":"المطففين", "hint":"The Dealers in Fraud, Defrauding, The Cheats, Those Who Give Short Measure", "indication":"", "level":"0"},
  {"word":"الإنشقاق", "hint":"The Rending Asunder, The Sundering, Splitting Open, The Splitting Asunder", "indication":"", "level":"0"},
  {"word":"البروج", "hint":"The Mansions Of The Stars, Constellations, The Great Constellations", "indication":"", "level":"0"},
  {"word":"الطارق", "hint":"The Night-Visitant, The Morning Star, The Nightcomer, That Which Comes in the Night", "indication":"", "level":"0"},
  {"word":"الأعلى", "hint":"The Most High, The All-Highest, Glory To Your Lord In The Highest", "indication":"", "level":"0"},
  {"word":"الغاشية", "hint":"The Overwhelming Event, The Overshadowing Event, The Pall", "indication":"", "level":"0"},
  {"word":"الفجر", "hint":"The Break of Day, The Daybreak, The Dawn", "indication":"", "level":"0"},
  {"word":"البلد", "hint":"The City, The Land", "indication":"", "level":"0"},
  {"word":"الشمس", "hint":"The Sun", "indication":"", "level":"0"},
  {"word":"الليل", "hint":"The Night", "indication":"", "level":"0"},
  {"word":"الضحى", "hint":"The Glorious Morning Light, The Forenoon, Morning Hours, Morning Bright, The Bright Morning Hours", "indication":"", "level":"0"},
  {"word":"الشرح", "hint":"The Expansion of Breast, Solace, Consolation, Relief, Patient, The Opening-Up of the Heart", "indication":"", "level":"0"},
  {"word":"التين", "hint":"The Fig Tree, The Fig", "indication":"", "level":"0"},
  {"word":"العلق", "hint":"The Clinging Clot, Clot of Blood, The Germ-Cell", "indication":"", "level":"0"},
  {"word":"القدر", "hint":"The Night of Honor, The Night of Decree, Power, Fate, Destiny", "indication":"", "level":"0"},
  {"word":"البينة", "hint":"The Clear Evidence, The Evidence of the Truth", "indication":"", "level":"0"},
  {"word":"الزلزلة", "hint":"The Earthquake", "indication":"", "level":"0"},
  {"word":"العاديات", "hint":"The Courser, The Chargers, The War Horse", "indication":"", "level":"0"},
  {"word":"القارعة", "hint":"The Striking Hour, The Great Calamity, The Stunning Blow, The Sudden Calamity", "indication":"", "level":"0"},
  {"word":"التكاثر", "hint":"The Piling Up, Rivalry in World Increase, Competition, Greed for More and More", "indication":"", "level":"0"},
  {"word":"العصر", "hint":"The Time, The Declining Day, The Epoch, The Flight of Time", "indication":"", "level":"0"},
  {"word":"الهمزة", "hint":"The Scandalmonger, The Traducer, The Gossipmonger, The Slanderer", "indication":"", "level":"0"},
  {"word":"الفيل", "hint":"The Elephant", "indication":"", "level":"0"},
  {"word":"قريش", "hint":"Quraysh", "indication":"", "level":"0"},
  {"word":"الماعون", "hint":"The Neighbourly Assistance, Small Kindnesses, Almsgiving, Assistance", "indication":"", "level":"0"},
  {"word":"الكوثر", "hint":"Abundance, Plenty, Good in Abundance", "indication":"", "level":"0"},
  {"word":"الكافرون", "hint":"The Disbelievers, The Kafirs, Those Who Deny the Truth", "indication":"", "level":"0"},
  {"word":"النصر", "hint":"The Help, Divine Support, Victory, Succour", "indication":"", "level":"0"},
  {"word":"المسد", "hint":"The Plaited Rope, The Palm Fibre, The Twisted Strands", "indication":"", "level":"0"},
  {"word":"الإخلاص", "hint":"Purity of Faith, The Fidelity, The Declaration of [God's] Perfection", "indication":"", "level":"0"},
  {"word":"الفلق", "hint":"The Daybreak, Dawn, The Rising Dawn", "indication":"", "level":"0"},
  {"word":"الناس", "hint":"Mankind, Men", "indication":"", "level":"0"}	

],[
{"word":"الرحمن", "hint":"The Exceedingly Compassionate, The Exceedingly Beneficent, The Exceedingly Gracious (to all of humanity and all creatures)", "indication":"", "level":"0"},
{"word":"الرحيم", "hint":"The Exceedingly Merciful", "indication":"", "level":"0"},
{"word":"الملك", "hint":"The King, The Sovereign", "indication":"", "level":"0"},
{"word":"القدوس", "hint":"The Holy, The Divine, The Pure, The Purifier", "indication":"", "level":"0"},
{"word":"السلام", "hint":"The Peace, The Source of Peace and Safety", "indication":"", "level":"0"},
{"word":"المؤمن", "hint":"The Granter of Security", "indication":"", "level":"0"},
{"word":"المهيمن", "hint":"The Controller", "indication":"", "level":"0"},
{"word":"العزيز", "hint":"The Almighty, The Invulnerable, The Honorable", "indication":"", "level":"0"},
{"word":"الجبار", "hint":"The Irresistible, The Compeller", "indication":"", "level":"0"},
{"word":"المتكبر", "hint":"The Majestic, The Supreme", "indication":"", "level":"0"},
{"word":"الخالق", "hint":"The Creator", "indication":"", "level":"0"},
{"word":"البارئ", "hint":"The Evolver, The Maker", "indication":"", "level":"0"},
{"word":"المصور", "hint":"The Fashioner, The Shaper, The Designer", "indication":"", "level":"0"},
{"word":"الغفار", "hint":"The Repeatedly Forgiving", "indication":"", "level":"0"},
{"word":"القهار", "hint":"The Subduer", "indication":"", "level":"0"},
{"word":"الوهاب", "hint":"The Bestower", "indication":"", "level":"0"},
{"word":"الرزاق", "hint":"The Provider, The Sustainer", "indication":"", "level":"0"},
{"word":"الفتاح", "hint":"The Opener, The Victory Giver", "indication":"", "level":"0"},
{"word":"العليم", "hint":"The All-Knowing, Omniscient", "indication":"", "level":"0"},
{"word":"القابض", "hint":"The Restrainer, The Straightener", "indication":"", "level":"0"},
{"word":"الباسط", "hint":"The Extender / Expander", "indication":"", "level":"0"},
{"word":"الخَافِض", "hint":"The Abaser, The Humiliator, The Downgrader", "indication":"", "level":"0"},
{"word":"الرافع", "hint":"The Exalter, The Upgrader", "indication":"", "level":"0"},
{"word":"المعز", "hint":"The Giver of Honor", "indication":"", "level":"0"},
{"word":"المذل", "hint":"The Giver of Dishonor", "indication":"", "level":"0"},
{"word":"السميع", "hint":"The All-Hearing", "indication":"", "level":"0"},
{"word":"البصير", "hint":"The All-Seeing", "indication":"", "level":"0"},
{"word":"الحكم", "hint":"The Judge, The Arbitrator", "indication":"", "level":"0"},
{"word":"العدل", "hint":"The Utterly Just", "indication":"", "level":"0"},
{"word":"اللطيف", "hint":"The Gentle, The Subtly Kind", "indication":"", "level":"0"},
{"word":"الخبير", "hint":"The All-Aware", "indication":"", "level":"0"},
{"word":"الحليم", "hint":"The Forbearing, The Indulgent", "indication":"", "level":"0"},
{"word":"العظيم", "hint":"The Great, The Magnificent", "indication":"", "level":"0"},
{"word":"الغفور", "hint":"The Much-Forgiving", "indication":"", "level":"0"},
{"word":"الشكور", "hint":"The Grateful", "indication":"", "level":"0"},
{"word":"العلي", "hint":"The Sublime", "indication":"", "level":"0"},
{"word":"الكبير", "hint":"The Great", "indication":"", "level":"0"},
{"word":"الحفيظ", "hint":"The Preserver", "indication":"", "level":"0"},
{"word":"المقيت", "hint":"The Nourisher", "indication":"", "level":"0"},
{"word":"الحسيب", "hint":"The Bringer of Judgment", "indication":"", "level":"0"},
{"word":"الجليل", "hint":"The Majestic, The Exalted", "indication":"", "level":"0"},
{"word":"الكريم", "hint":"The Bountiful, The Generous", "indication":"", "level":"0"},
{"word":"الرقيب", "hint":"The Watchful", "indication":"", "level":"0"},
{"word":"المجيب", "hint":"The Responsive, The Answerer", "indication":"", "level":"0"},
{"word":"الواسع", "hint":"The Vast, The All-Embracing, The Omnipresent, The Boundless", "indication":"", "level":"0"},
{"word":"الحكيم", "hint":"The All-Wise", "indication":"", "level":"0"},
{"word":"الودود", "hint":"The Loving", "indication":"", "level":"0"},
{"word":"المجيد", "hint":"The All-Glorious, The Majestic", "indication":"", "level":"0"},
{"word":"الباعث", "hint":"The Resurrector", "indication":"", "level":"0"},
{"word":"الشهيد", "hint":"The Witness", "indication":"", "level":"0"},
{"word":"الحق", "hint":"The Truth, The Reality", "indication":"", "level":"0"},
{"word":"الوكيل", "hint":"The Trustee, The Dependable, The Advocate", "indication":"", "level":"0"},
{"word":"القوي", "hint":"The Strong", "indication":"", "level":"0"},
{"word":"المتين", "hint":"The Firm, The Steadfast", "indication":"", "level":"0"},
{"word":"الولي", "hint":"The Friend, Patron and Helper", "indication":"", "level":"0"},
{"word":"الحميد", "hint":"The All Praiseworthy", "indication":"", "level":"0"},
{"word":"المحصي", "hint":"The Accounter, The Numberer of All", "indication":"", "level":"0"},
{"word":"المبدئ", "hint":"The Originator, The Producer, The Initiator", "indication":"", "level":"0"},
{"word":"المعيد", "hint":"The Restorer, The Reinstater Who Brings Back All", "indication":"", "level":"0"},
{"word":"المحيي", "hint":"The Giver of Life", "indication":"", "level":"0"},
{"word":"المميت", "hint":"The Bringer of Death", "indication":"", "level":"0"},
{"word":"الحي", "hint":"The Living", "indication":"", "level":"0"},
{"word":"القيوم", "hint":"The Subsisting, The Independent", "indication":"", "level":"0"},
{"word":"الواجد", "hint":"The Perceiver, The Finder, The Unfailing", "indication":"", "level":"0"},
{"word":"الماجد", "hint":"The Illustrious, The Magnificent", "indication":"", "level":"0"},
{"word":"الواحد", "hint":"The Unique, The Single", "indication":"", "level":"0"},
{"word":"الاحد", "hint":"The One, The Indivisible", "indication":"", "level":"0"},
{"word":"الصمد", "hint":"The Eternal, The Absolute, The Self-Sufficient", "indication":"", "level":"0"},
{"word":"القادر", "hint":"The All-Powerful, He Who is able to do Everything", "indication":"", "level":"0"},
{"word":"المقتدر", "hint":"The Determiner, The Dominant", "indication":"", "level":"0"},
{"word":"المقدم", "hint":"The Expediter, He Who Brings Forward", "indication":"", "level":"0"},
{"word":"المؤخر", "hint":"The Delayer, He Who Puts Far Away", "indication":"", "level":"0"},
{"word":"الأول", "hint":"The First, The Beginning-less", "indication":"", "level":"0"},
{"word":"الأخر", "hint":"The Last, The Endless", "indication":"", "level":"0"},
{"word":"الظاهر", "hint":"The Manifest, The Evident, The Outer", "indication":"", "level":"0"},
{"word":"الباطن", "hint":"The Hidden, The Unmanifest, The Inner", "indication":"", "level":"0"},
{"word":"الوالي", "hint":"The Patron, The Protecting Friend, The Friendly Lord", "indication":"", "level":"0"},
{"word":"المتعالي", "hint":"The Supremely Exalted, The Most High", "indication":"", "level":"0"},
{"word":"البر", "hint":"The Good, The Beneficent", "indication":"", "level":"0"},
{"word":"التواب", "hint":"The Ever-Returning, Ever-Relenting", "indication":"", "level":"0"},
{"word":"المنتقم", "hint":"The Avenger", "indication":"", "level":"0"},
{"word":"العفو", "hint":"The Pardoner, The Effacer, The Forgiver", "indication":"", "level":"0"},
{"word":"الرؤوف", "hint":"The Kind, The Pitying", "indication":"", "level":"0"},
{"word":"مالك الملك", "hint":"Owner of all Sovereignty", "indication":"", "level":"0"},
{"word":"ذو الجلال والإكرام", "hint":"Lord of Majesty and Generosity", "indication":"", "level":"0"},
{"word":"المقسط", "hint":"The Equitable, The Requiter", "indication":"", "level":"0"},
{"word":"الجامع", "hint":"The Gatherer, The Unifier", "indication":"", "level":"0"},
{"word":"الغني", "hint":"The Rich, The Independent", "indication":"", "level":"0"},
{"word":"المغني", "hint":"The Enricher, The Emancipator", "indication":"", "level":"0"},
{"word":"المانع", "hint":"The Withholder, The Shielder, The Defender", "indication":"", "level":"0"},
{"word":"الضار", "hint":"The Distressor, The Harmer, The Afflictor", "indication":"", "level":"0"},
{"word":"النافع", "hint":"The Propitious, The Benefactor, The Source of Good", "indication":"", "level":"0"},
{"word":"النور", "hint":"The Light", "indication":"", "level":"0"},
{"word":"الهادي", "hint":"The Guide, The Way", "indication":"", "level":"0"},
{"word":"البديع", "hint":"The Incomparable, The Unattainable, The Beautiful", "indication":"", "level":"0"},
{"word":"الباقي", "hint":"The Immutable, The Infinite, The Everlasting", "indication":"", "level":"0"},
{"word":"الوارث", "hint":"The Heir, The Inheritor of All", "indication":"", "level":"0"},
{"word":"الرشيد", "hint":"The Guide to the Right Path", "indication":"", "level":"0"},
{"word":"الصبور", "hint":"The Timeless, The Patient", "indication":"", "level":"0"},

],[
  {"word":"محمد", "hint":"خاتم النبيين", "indication":"", "level":"0"},
  {"word":"عيسى", "hint":"ابن مريم", "indication":"", "level":"0"},
  {"word":"موسى", "hint":"كليم الله", "indication":"", "level":"0"},
  {"word":"هارون", "hint":"أخو موسى", "indication":"", "level":"0"},
  {"word":"أيوب", "hint":"في المَثَل، يقولون : صَبْرُ ... ؟", "indication":"", "level":"0"},
  {"word":"نوح", "hint":"أبو البشر الثاني والذي بنى السفينة", "indication":"", "level":"0"},
  {"word":"آدم", "hint":"أب البشر", "indication":"", "level":"0"},
  {"word":"داوود", "hint":"نبي ملك", "indication":"", "level":"0"},
  {"word":"سليمان", "hint":"نبي ملك", "indication":"", "level":"0"},
  {"word":"صالح", "hint":"معجزة الناقة", "indication":"", "level":"0"},
  {"word":"إبراهيم", "hint":"أبو الأنبياء", "indication":"", "level":"0"},
  {"word":"إسماعيل", "hint":"ابن إبراهيم وأبو العرب", "indication":"", "level":"0"},
  {"word":"إسحاق", "hint":"ابن إبراهيم", "indication":"", "level":"0"},
  {"word":"يعقوب", "hint":"أبو يوسف", "indication":"", "level":"0"},
  {"word":"يوسف", "hint":"قصة الذئب", "indication":"", "level":"0"},
  {"word":"زكرياء", "hint":"أبو يحي", "indication":"", "level":"0"},
  {"word":"يحيى", "hint":"ابن زكريا ", "indication":"", "level":"0"},
  {"word":" يونس", "hint":"ذو النون (الحوت)", "indication":"", "level":"0"},
  {"word":"شعيب", "hint":"أرسله الله إلى مدين", "indication":"", "level":"0"},
  {"word":"هود", "hint":"نبي عربي", "indication":"", "level":"0"},
  {"word":"لوط", "hint":"ابن أخ إبراهيم", "indication":"", "level":"0"},
  {"word":"إدريس", "hint":"بعد آدم", "indication":"", "level":"0"},
], [
  {"word":"علي بن أبي طالب", "hint":"ابن عم رسول الله", "indication":"", "level":"0"},
  {"word":"عمر بن الخطاب", "hint":"الفاروق", "indication":"", "level":"0"},
  {"word":"أبو بكر", "hint":"الصِدّيق", "indication":"", "level":"0"},
  {"word":"عثمان بن عفان", "hint":"ثالِث خليفة", "indication":"", "level":"0"},
  {"word":"أبو هريرة", "hint":"هو ذو النورَيْن", "indication":"", "level":"0"},
  {"word":"بلال بن رباح", "hint":"مُؤَذِّنُ الرسول", "indication":"", "level":"0"},
  {"word":"حمزة", "hint":"أسد الله", "indication":"", "level":"0"},
  {"word":"خالد بن الوليد ", "hint":"سيف الله المسلول", "indication":"", "level":"0"},
  {"word":"عبدالله بن مسعود", "hint":"One of the four that the Prophet asked us to learn the recitation of Qur'an from<br/> سادس من أسلم من الصحابة، وأول من جهر بالقرآن", "indication":"", "level":"0"},
  {"word":"عبدالله بن عباس", "hint":"حَبْرُ الأُمة وترْجُمان القرآن", "indication":"", "level":"0"},

],[
  {"word":"رحمة", "hint":"Mercy", "indication":"", "level":"0"},
  {"word":"بركة", "hint":"blessing", "indication":"", "level":"0"},
], [
  {"word":"جمل", "hint":"سفينة الصحراء", "indication":"", "level":"0"},
  {"word":"كبش", "hint":"العيد", "indication":"", "level":"0"},
  {"word":"حمار", "hint":"صبور", "indication":"", "level":"0"},
  {"word":"حصان", "hint":"يَرْكَبُهُ الفارِس", "indication":"", "level":"0"},
  {"word":"بقرة", "hint":"تُعطينا الحليب", "indication":"", "level":"0"},
  {"word":"دجاجة", "hint":"تُعطينا البيض", "indication":"", "level":"0"},
  {"word":"أرنب", "hint":"حيوان صغير جميل يُحبِهُ الأطفال", "indication":"", "level":"0"},
  {"word":"ديك", "hint":"يَصيحُ كل صباح كوكو ...كوكو", "indication":"", "level":"0"},
  {"word":"بطة", "hint":"طائر يُحبُّ الماء", "indication":"", "level":"0"},
  {"word":"خروف", "hint":"العيد", "indication":"", "level":"0"},
], [
  {"word":"نمر", "hint":"قط كبير", "indication":"", "level":"0"},
  {"word":"أسد", "hint":"قط كبير", "indication":"", "level":"0"},
], [
  {"word":"اليمن", "hint":"بِلاد سَبأ", "indication":"", "level":"0"},
  {"word":"عمان", "hint":"البلد الوحيد الذي فيه يبدأ بحرف العين", "indication":"", "level":"0"},
  {"word":"قطر", "hint":"في جزيرة العرب", "indication":"", "level":"0"},
  {"word":"الكويت", "hint":"في جزيرة العرب", "indication":"", "level":"0"},
  {"word":" السعودية", "hint":"بِلادُ الحَرَمَيْن", "indication":"", "level":"0"},
  {"word":"سوريا", "hint":"في الشام", "indication":"", "level":"0"},
  {"word":"الأردن", "hint":"بين الشام وجزيرة العرب", "indication":"", "level":"0"},
  {"word":"العراق", "hint":"بِلاد السوماريين", "indication":"", "level":"0"},
  {"word":"لبنان", "hint":"عاصِمَتُها بيروت ", "indication":"", "level":"0"},
  {"word":"فلسطين", "hint":"القدس", "indication":"", "level":"0"},
  {"word":"البحرين", "hint":"2 * بحر", "indication":"", "level":"0"},
  {"word":"مصر", "hint":"الأهرام", "indication":"", "level":"0"},
  {"word":"المغرب", "hint":"اسم صلاة", "indication":"", "level":"0"},
  {"word":"تونس", "hint":"في شمال إفريقيا", "indication":"", "level":"0"},
  {"word":"الجزائر", "hint":"في شمال إفريقيا", "indication":"", "level":"0"},
  {"word":"ليبيا", "hint":"في شمال إفريقيا", "indication":"", "level":"0"},
], [
  {"word":"القدس", "hint":"the first Qibla", "indication":"", "level":"0"},
], [
  {"word":"أبيض", "hint":"white", "indication":"", "level":"0"},
  {"word":"أسود", "hint":"black", "indication":"", "level":"0"},
  {"word":"أخضر", "hint":"Green", "indication":"", "level":"0"},
  {"word":"أزرق", "hint":"Blue", "indication":"", "level":"0"},
  {"word":"أحمر", "hint":"Red", "indication":"", "level":"0"},
  {"word":"أصفر", "hint":"yellow", "indication":"", "level":"0"},
  {"word":"بني", "hint":"brown", "indication":"", "level":"0"},
  {"word":"برتقالي", "hint":"orange", "indication":"", "level":"0"},
  {"word":"وردي", "hint":"rose", "indication":"", "level":"0"},
  {"word":"رمادي", "hint":"grey", "indication":"", "level":"0"},
  {"word":"أشقر", "hint":"Blond", "indication":"", "level":"0"},
  {"word":"أسمر", "hint":"dark or tan", "indication":"", "level":"0"},
  {"word":"أصهب", "hint":"ginger, (this is why Suhaib Ar-rumi was called like that)", "indication":"", "level":"0"},
],[

  {"word":"تفاح", "hint":"pomme", "indication":"", "level":"0"},
  {"word":"رمان", "hint":"grenade", "indication":"", "level":"0"},
  {"word":"برتقال", "hint":"orange", "indication":"", "level":"0"},
  {"word":"ليمون ", "hint":"citron", "indication":"", "level":"0"},
  {"word":"موز", "hint":"banane", "indication":"", "level":"0"},
  {"word":"تين", "hint":"figue", "indication":"", "level":"0"},
  {"word":"تمر ", "hint":"datte", "indication":"", "level":"0"},
  {"word":"عنب", "hint":"raisin", "indication":"", "level":"0"},
  {"word":"توت", "hint":"myrtille", "indication":"", "level":"0"},
  {"word":"كرز", "hint":"cerises", "indication":"", "level":"0"},
  {"word":"فرولة", "hint":"fraise", "indication":"", "level":"0"},
  {"word":"بطيخ", "hint":"pastèque/melon", "indication":"", "level":"0"},
  {"word":"مشمش", "hint":"abricot", "indication":"", "level":"0"},
  {"word":"خوخ", "hint":"pêches", "indication":"", "level":"0"},
  {"word":"إجاص", "hint":"poire", "indication":"", "level":"0"},
  {"word":"برقوق", "hint":"prune", "indication":"", "level":"0"},
  {"word":"أناناس", "hint":"ananas", "indication":"", "level":"0"},
  {"word":"كيوي", "hint":"kiwi", "indication":"", "level":"0"},
  {"word":"مندرين", "hint":"mandarine", "indication":"", "level":"0"},
  {"word":"شمام", "hint":"cantaloup", "indication":"", "level":"0"},

],[
  {"word":"الطماطم", "hint":"tomato", "indication":"", "level":"1"},
  {"word":"البندورة", "hint":"tomato", "indication":"", "level":"4"},
  {"word":"البطاطا", "hint":"potato", "indication":"", "level":"1"},
  {"word":"البطاطس", "hint":"potato", "indication":"", "level":"3"},
  {"word":"جزر", "hint":"carrot(s)", "indication":"", "level":"1"},
  {"word":"بصل", "hint":"onion(s)", "indication":"", "level":"1"},
  {"word":"ثوم", "hint":"garlic", "indication":"", "level":"1"},
  {"word":"فلفل", "hint":"pepper", "indication":"", "level":"1"},
  {"word":"يقطين", "hint":"pumpkin", "indication":"", "level":"2"},
  {"word":"خيار", "hint":"cucumber", "indication":"", "level":"2"},
  {"word":"قثاء", "hint":"armenian cucumber", "indication":"", "level":"2"},
  {"word":"الخس", "hint":"salad", "indication":"", "level":"2"},
  {"word":"ذرة", "hint":"corn", "indication":"", "level":"2"},
  {"word":"فاصوليا", "hint":"beans", "indication":"", "level":"2"},
  {"word":"فاصوليا خضراء", "hint":"green beans", "indication":"", "level":"2"},
  {"word":"بازلاء", "hint":"peas", "indication":"", "level":"2"},
  {"word":"الباذنجان", "hint":"aubergine", "indication":"", "level":"2"},
  {"word":"فجل", "hint":"radishes", "indication":"", "level":"2"},
  {"word":"شمندر", "hint":"beet", "indication":"", "level":"2"},
  {"word":"بنجر", "hint":"beet", "indication":"", "level":"2"},
  {"word":"قرنبيط", "hint":"cauliflower", "indication":"", "level":"2"},
  {"word":"الكرنب", "hint":"cabbage", "indication":"", "level":"2"},
  {"word":"سلق", "hint":"chard", "indication":"", "level":"2"},
  {"word":"سبانخ", "hint":"spinach", "indication":"", "level":"2"},
],[
  {"word":"نبات", "hint":"plant", "indication":"", "level":"0"},
  {"word":"شجر", "hint":"tree", "indication":"", "level":"0"},
  {"word":"نخل", "hint":"palm tree", "indication":"", "level":"0"},
  {"word":"شجيرة", "hint":"bush", "indication":"", "level":"0"},
  {"word":"قصب", "hint":"cane", "indication":"", "level":"0"},
  {"word":"عشب", "hint":"grass", "indication":"", "level":"0"},
  {"word":"سنبلة", "hint":"spike", "indication":"", "level":"0"},
  {"word":"فطر", "hint":"fungus", "indication":"", "level":"0"},

],[
  {"word":"باب", "hint":"a door", "indication":"", "level":"0"},
],[
  {"word":"عم", "hint":"uncle", "indication":"", "level":"0"},
],[

],[

]


];
